projects:
  codexeapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/*.ts
    excludes:
      - ./amplify/**
      - src/graphql/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
